# https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
apiVersion: 1
deleteDatasources:
  - name: InfluxDB

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: arbitraryDB
    user: admin
    password: admin
    isDefault: true
    editable: true
